### ISSUE TITLE
MIMS f

### ISSUE THREAD

**Issue by fracnesco** [mi-creative/mi-gen#2]
After using MIMS for max for some time it seems to have stopped working properly, if I write a model and click on Parse Model the generated gen~ code is just and empty model. It works only if I load an existing .mdl file, but then I am not able to change it. Also I don't get any errors in the Error Reports tab nor in the MIMS compiler state even if I do typos. I am using Max latest version and MI gen latest version on MacOs high Sierra 10.13.5

**Comment by jameslnrd** [comment]
Hi, sorry for not seeing your issue sooner.
A recent change caused a broken dependency to math.js if it wasn't installed on your system, causing an error in the MIMS4Max main NodeJS script. I just commited a fix, let me know if it works on your end!
